"""Create a clean, disposable Git workspace for the RepoPilot fix demo."""

from __future__ import annotations

import argparse
import os
import shutil
import stat
import subprocess
from collections.abc import Callable
from pathlib import Path
from types import TracebackType

_SOURCE = Path(__file__).resolve().parent / "demo-repo"
_DEFAULT_DESTINATION = Path("data/demo-workspace")
_COPY_IGNORE = shutil.ignore_patterns("__pycache__", ".pytest_cache", "*.py[cod]")
_GENERATED_MARKER = Path(".git") / "repopilot-demo-workspace"


def _remove_readonly(
    function: Callable[[str], object],
    path: str,
    error_info: tuple[type[BaseException], BaseException, TracebackType | None],
) -> None:
    error = error_info[1]
    if not isinstance(error, PermissionError):
        raise error
    os.chmod(path, stat.S_IWRITE)
    function(path)


def _run_git(workspace: Path, *args: str) -> str:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=workspace,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise RuntimeError("Git is required but was not found on PATH.") from exc

    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip() or "no error output"
        command = " ".join(["git", *args])
        raise RuntimeError(f"{command} failed: {detail}")
    return completed.stdout.strip()


def _resolved_destination(destination: Path) -> Path:
    requested = destination.expanduser()
    if requested.is_symlink():
        raise ValueError("The destination must not be a symbolic link.")

    resolved = requested.resolve()
    source = _SOURCE.resolve()
    if resolved == resolved.parent:
        raise ValueError("The destination must not be a filesystem root.")
    if resolved == source or resolved.is_relative_to(source) or source.is_relative_to(resolved):
        raise ValueError("The destination must not contain or be inside the source fixture.")
    return resolved


def prepare_demo(destination: Path) -> Path:
    """Recreate destination from the fixture and make one clean baseline commit."""
    workspace = _resolved_destination(destination)
    if (_SOURCE / ".git").exists():
        raise RuntimeError("The source fixture must not contain a nested Git repository.")
    if workspace.exists():
        if not workspace.is_dir():
            raise ValueError("The destination exists and is not a directory.")
        if not (workspace / _GENERATED_MARKER).is_file():
            raise ValueError(
                "Refusing to replace an existing directory that was not generated by this script."
            )
        shutil.rmtree(workspace, onerror=_remove_readonly)

    workspace.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(_SOURCE, workspace, ignore=_COPY_IGNORE)

    _run_git(workspace, "init", "-b", "main")
    _run_git(workspace, "config", "user.name", "RepoPilot Demo")
    _run_git(workspace, "config", "user.email", "demo@repopilot.local")
    _run_git(workspace, "config", "core.autocrlf", "false")
    (workspace / _GENERATED_MARKER).write_text(
        "generated by examples/prepare_demo.py\n",
        encoding="utf-8",
    )
    _run_git(workspace, "add", "--all")
    _run_git(
        workspace,
        "commit",
        "--no-gpg-sign",
        "--no-verify",
        "-m",
        "chore: establish demo baseline",
    )

    status = _run_git(workspace, "status", "--porcelain")
    if status:
        raise RuntimeError(f"Prepared workspace is not clean: {status}")
    return workspace


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dest",
        type=Path,
        default=_DEFAULT_DESTINATION,
        help=(f"Disposable workspace to recreate (default: {_DEFAULT_DESTINATION.as_posix()})."),
    )
    return parser


def main() -> None:
    args = _build_parser().parse_args()
    try:
        workspace = prepare_demo(args.dest)
    except (OSError, RuntimeError, ValueError) as exc:
        raise SystemExit(f"Failed to prepare demo workspace: {exc}") from exc
    print(f"Prepared clean demo workspace: {workspace}")


if __name__ == "__main__":
    main()
