[theme]
base = "light"
primaryColor = "#7D3126"
backgroundColor = "#F4EFE6"
secondaryBackgroundColor = "#E9E0D2"
textColor = "#211E1A"
codeBackgroundColor = "#E1D8CA"
borderColor = "#B4A998"
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
baseRadius = "none"
buttonRadius = "none"
showWidgetBorder = true
